import { type NextPage } from "next";
import Head from "next/head";
import {
    Container,
    Flex,
    Heading,
    Table,
    Thead,
    Tbody,
    Tfoot,
    Tr,
    Th,
    Td,
    TableCaption,
    TableContainer,
} from "@chakra-ui/react";

// COMPONENTS
import {api} from "@/utils/api";

const Activities: NextPage = () => {

    const {data: logs, isFetching} = api.user.getAccountActivity.useQuery()

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Container
                maxW={'container.xl'}
                p={'2'}
            >
                <Flex
                    flexDir={'column'}
                    gap={'2rem'}
                >
                    <Heading
                        size={'md'}
                    >
                        Account Summary
                    </Heading>
                    <TableContainer
                        bg={'white'}
                    >
                        <Table variant='striped' size={'sm'}>
                            <Thead
                                bg={'primary.50'}
                            >
                                <Tr>
                                    <Th>Sl No</Th>
                                    <Th>Currency</Th>
                                    <Th>Txn Id</Th>
                                    <Th>Txn Type</Th>
                                    <Th>Date</Th>
                                    <Th>Amount</Th>
                                    <Th>Total Balance</Th>
                                </Tr>
                            </Thead>
                            <Tbody>
                                {
                                    isFetching && <Tr>
                                        <Td colSpan={7}>Loading...</Td>
                                    </Tr>
                                }
                                {
                                    logs && logs?.activities?.map((activity, index) => {
                                        return <Tr key={activity.id}>
                                            <Td>{index + 1}</Td>
                                            <Td>{activity.currency}</Td>
                                            <Td>{activity.txn_id}</Td>
                                            <Td>{activity.txn_type}</Td>
                                            <Td>{activity.date}</Td>
                                            <Td>{activity.amount}</Td>
                                            <Td>{activity.total_balance}</Td>
                                        </Tr>
                                    })
                                }
                            </Tbody>
                        </Table>
                    </TableContainer>
                </Flex>
            </Container>
        </>
    );
};

export default Activities;
