import Head from "next/head";
import Exchange from "@/components/ICO/Exchange";
import {Container, Flex, Grid, useDisclosure} from "@chakra-ui/react";
import Stats from "@/components/ICO/Stats";
import LockedSICA from "@/components/Balance/LockedSICA";
import Wallet from "@/components/Balance/Wallet";
import BonusSICA from "@/components/Balance/BonusSICA";

const Buy = () => {

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <Container
                    maxW={{
                        base: 'container.sm',
                        lg: 'container.md'
                    }}
                >
                    <Grid
                        gridTemplateColumns={{
                            base: '1fr',
                            lg: '65% 35%',
                        }}
                        gap={'1rem'}
                    >
                        <Flex
                            flexDir={'column'}
                            gap={'20px'}
                        >
                            <Stats />
                            <Grid
                                gridTemplateColumns={{
                                    base: '1fr',
                                }}
                                gap={'10px'}
                                display={{
                                    base: 'grid',
                                    lg: 'none'
                                }}
                            >
                                <Wallet />
                                <Grid
                                    gridTemplateColumns={'repeat(2, 1fr)'}
                                    gap={'10px'}
                                >
                                    <LockedSICA />
                                </Grid>
                            </Grid>
                            <Exchange />
                        </Flex>
                        <Flex
                            display={{
                                base: 'none',
                                lg: 'flex'
                            }}
                            flexDir={'column'}
                            gap={'1rem'}
                        >
                            <LockedSICA />
                            <BonusSICA />
                            <Wallet />
                        </Flex>
                    </Grid>


                </Container>
            </main>
        </>
    )
}

export default Buy