import { type NextPage } from "next";
import Head from "next/head";
import {
    Container,
    Flex,
    Heading,
    Table,
    Thead,
    Tbody,
    Tfoot,
    Tr,
    Th,
    Td,
    TableCaption,
    TableContainer, Text,
} from "@chakra-ui/react";

// COMPONENTS
import {api} from "@/utils/api";

const CEM: NextPage = () => {

    return (
        <>
            <Head>
                <title>Carbon Exchange Marketplace</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Container
                maxW={'container.xl'}
                p={'2'}
            >
                <Flex
                    flexDir={'column'}
                    gap={'2rem'}
                >
                    <Heading
                        size={'md'}
                    >
                        Carbon Exchange Marketplace
                    </Heading>
                    <Flex
                        w={{
                            base: '100%',
                            lg: '50%'
                        }}
                    >
                        <Text>
                            SICA Carbon Exchange Marketplace (CEM) can help you source and purchase certified Carbon Offsets Live Website Carbon Counter Live Carbon Impact Page Climate Action Coach Participate in UN SDGs.
                        </Text>
                    </Flex>
                </Flex>
            </Container>
        </>
    );
};

export default CEM;
