import { type NextPage } from "next";
import Head from "next/head";
import {
    Container,
    Flex,
    Heading,
    Table,
    Thead,
    Tbody,
    Tfoot,
    Tr,
    Th,
    Td,
    TableCaption,
    TableContainer, Text,
} from "@chakra-ui/react";

// COMPONENTS
import {api} from "@/utils/api";

const Swipe: NextPage = () => {

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Container
                maxW={'container.xl'}
                p={'2'}
            >
                <Flex
                    flexDir={'column'}
                    gap={'2rem'}
                >
                    <Heading
                        size={'md'}
                    >
                        SICA SWIPE
                    </Heading>
                    <Flex
                        w={{
                            base: '100%',
                            lg: '50%'
                        }}
                    >
                        <Text>
                            A Prepaid Card is offered to our investors for ease of payment and smooth conversion of crypto to fiat. This comes up with QR/ NFC feature and enable you to store multiple currencies pegged with SICA
                        </Text>
                    </Flex>
                </Flex>
            </Container>
        </>
    );
};

export default Swipe;
