import { type NextPage } from "next";
import Head from "next/head";
import {
    Container,
    Flex,
    Heading,
    Text,
} from "@chakra-ui/react";

// COMPONENTS
import {api} from "@/utils/api";

const Wealth: NextPage = () => {

    return (
        <>
            <Head>
                <title>Wealth Management</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Container
                maxW={'container.xl'}
                p={'2'}
            >
                <Flex
                    flexDir={'column'}
                    gap={'2rem'}
                >
                    <Heading
                        size={'md'}
                    >
                        Wealth Management
                    </Heading>
                    <Flex
                        w={{
                            base: '100%',
                            lg: '50%'
                        }}
                    >
                        <Text>
                            Plan your savings and let your wealth grow with our Smart Wealth and portfolio management services with a tailor made solution
                        </Text>
                    </Flex>
                </Flex>
            </Container>
        </>
    );
};

export default Wealth;
